export const SET_POKEMONS = 'POKEMONS/SET_POKEMONS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const SELECT_POKEMON = 'SELECT_POKEMON';
export const SET_FILTER = 'FILTERS/SET_FILTER';
export const SET_FILTERS = 'FILTERS/SET_FILTERS';
